receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlp/traces:
    # httpだと /v1/traces に送ってしまうのでgRPCの方に送る
    endpoint: http://jaeger:4317
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
  otlphttp/metrics:
    endpoint: http://prometheus:9090/api/v1/otlp
  otlp/oteltui:
    endpoint: oteltui:4317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces, otlp/oteltui]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/metrics, otlp/oteltui]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs, otlp/oteltui]
