otel:
  propagators:
    - tracecontext
  service:
    name: todo-app
  instrumentation:
    micrometer:
      enabled: true
spring:
  sql:
    init:
      mode: always
backend:
  host-name: localhost
  port: 8080